# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76111402de1ff43ee7c42bde8ae9d30fede7f6ec3576f24acbf32e9a71e816c2e7eb9f48a2dd434d70b6aa0b7fc8d3afb391a6bccd12445e327372826e080343

test:
  secret_key_base: 7248365110a61e109015e5827653526db8cb7f3cbb24173a496e7ef11685c51274c67db1e4f066fb16ba6867772a2d8e7da083b97d22462d8566df9277955098

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
